/**
 * Import hand-supplied cover images for songs that aren't on pumpproplus.
 *
 * Drop files named "<songId>.<png|jpg|jpeg|webp>" into the repo-root `incoming/`
 * folder (full-size / 16:9 is fine — they're center-cropped to a 256px square,
 * same as fetch-thumbs), then run `npm run import:covers`. It writes
 * app/assets/thumbs/<id>.jpg and regenerates app/src/thumbs.ts.
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, extname, basename } from "node:path";
import { Jimp } from "jimp";

const pipelineRoot = join(import.meta.dirname, "..");
const repoRoot = join(pipelineRoot, "..");
const incomingDir = join(repoRoot, "incoming");
const thumbsDir = join(repoRoot, "app", "assets", "thumbs");
const thumbsModule = join(repoRoot, "app", "src", "thumbs.ts");

const EXT = new Set([".png", ".jpg", ".jpeg", ".webp"]);

async function main() {
  if (!existsSync(incomingDir)) {
    console.error(`No incoming/ folder at ${incomingDir}`);
    process.exit(1);
  }
  const files = readdirSync(incomingDir).filter((f) => EXT.has(extname(f).toLowerCase()));
  let n = 0;
  for (const f of files) {
    const id = basename(f, extname(f));
    const img = await Jimp.fromBuffer(readFileSync(join(incomingDir, f)));
    img.cover({ w: 256, h: 256 }); // scale-to-fill + center-crop, like fetch-thumbs
    const jpg = await img.getBuffer("image/jpeg", { quality: 82 });
    writeFileSync(join(thumbsDir, id + ".jpg"), jpg);
    console.log(`  ${f} -> thumbs/${id}.jpg (${jpg.length} bytes)`);
    n++;
  }

  // regenerate the require map from whatever .jpg files exist (mirrors fetch-thumbs)
  const ids = readdirSync(thumbsDir)
    .filter((f) => f.endsWith(".jpg"))
    .map((f) => f.slice(0, -4))
    .sort();
  const lines = ids.map((id) => `  ${JSON.stringify(id)}: require(${JSON.stringify("../assets/thumbs/" + id + ".jpg")}),`);
  const module = [
    "// Map of song id -> bundled cover thumbnail (256px JPEG). Generated by",
    "// pipeline/scripts/fetch-thumbs.ts — do not edit by hand.",
    "export const THUMBS: Record<string, number> = {",
    ...lines,
    "};",
    "",
  ].join("\n");
  writeFileSync(thumbsModule, module);
  console.log(`Imported ${n} cover(s); thumbs.ts now lists ${ids.length} covers.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
